### ISSUE TITLE
Unicode not working during runtime?

### ISSUE THREAD

**Issue by PauloFDO** [Shinmera/promptfont#11]
First of all thank you so much! I got super excited when I found this, it is beyond perfect, my only issue:

It works very well when you pre-populate a textbox with the correct text, for example `Press <color=#FF8424>\u243A</color>` shows me exactly what I want to see at all times, but if during runtime I add the unicode to the string things do not seem to work at all.

if I have` Press <color=#FF8424>'This will be replaced'</color>` 

and update the string to `Press <color=#FF8424>\u243A</color>`  Unity displays `Press \u243A`, if I manually change anything in the inspector of the textmesh Pro it snaps back into place and shows the button correctly, any idea of how to go around that? I've spent many hours with no result

**Comment by Shinmera** [comment]
Sorry, no clue. I don't use Unity, and this seems like a very unity specific problem, so I have no advice. You'll have more luck on unity specific communities.
