### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by gman003** [Shinmera/promptfont#16]
While going through the docs page, I found a few things that were either wrong, or confusing. None of these are high-priority issues, but they do make it a bit harder to find what you're looking for, or for a newcomer like me to see if this font is usable for a given purpose.

Errors:
+ U+E003, U+2209, U+220A, and U+220B are labeled "Ayaeno", should be "Ayaneo".
+ U+E006 is "Rog Alloy", should be "ROG Ally". U+E005, U+2212, and U+2213 should also capitalize the acronym properly. It's kind of a dorky acronym, but it is an acronym.

Confusing:
+ U+220C and U+220D ought to be "Ayaneo" instead of "AYN" for consistency.
+ Are U+22B9, U+21BA, and U+21BB for analog stick *clicks*, commonly called L3/R3? That's my best guess, and the one thing I can't see anywhere else, but it ought to be explicitly said.
+ What is the difference between U+21B2 and U+21DC (and B3/DD)? From another issue I think the latter are for partial or soft pulls, but that's not at all clear from the names.
+ Is there a "Dpad Left/Up" and "Dpad Down/Right", to go with U+21B4 and U+21B5, and mirroring U+2280-2283? Or are they just missing from the docs?
+ Several icons are sorted strangely. You probably shouldn't rearrange the codepoints just for this, but the docs at least ought to put U+21F5 Right Analog Up/Down next to U+21C6 Right Analog Left/Right.

In general, I also found the Gamepad section to be disorganized and hard to read. Twelve dozen icons in one big blob is not great. I think it's gotten big enough to need breaking up into sub-categories. My preference would be to split the section up into "Analog Sticks", "Primary Face Buttons", "Dpad", "Triggers + Bumpers", and "Menu Buttons", but I could also see "Common", "PlayStation", "Xbox", "Nintendo", "Steam", etc. working well.

I can make a PR if you'd like but some of these are points I'm unsure about, and would like clarification myself. This does look like a very useful project.

**Comment by Shinmera** [comment]
- I named those after the files that were submitted.
- Yes
- Yes
- No, it's on the todo.
- The html page is auto generated based on the json file. It sorts things by their code point, since there's nothing else to go by.

**Comment by Shinmera** [comment]
I've added a simple dynamic search field to the web page.

**Comment by gman003** [comment]
Oh, that is useful! I can take a stab at tagging everything when I find some time, seems like a good first issue.

If U+22B9 etc. aren't meant to be L3/R3 clicks, what *are* they intended for? So I can tag them appropriately.

**Comment by Shinmera** [comment]
They *are* for analog clicks? I replied with Yes to that question.

**Comment by CasperH2O** [comment]
Hey @gman003 , this comment:

> U+220C and U+220D ought to be "Ayaneo" instead of "AYN" for consistency.

Is actually not correct. I realize it's confusing, there is a company called Ayaneo and AYN. AYN makes the Odin and Loki devices. See product page here: https://droix.net/nl/product/ayn-loki/
