### ISSUE TITLE
Incorrect name of an Xbox button

### ISSUE THREAD

**Issue by redphx** [Shinmera/promptfont#19]
[According to Xbox](https://support.xbox.com/en-US/help/hardware-network/controller/get-to-know-your-xbox-series-x-s-controller), this ["Share/Capture" button](https://github.com/Shinmera/promptfont/blob/master/glyphs/gamepad/button-share.svg) on the Xbox controller should be called the "View" button instead. The "Share" button has a different icon.

<img width="733" alt="image" src="https://github.com/Shinmera/promptfont/assets/96280/f4496571-57e1-4300-8f42-19ae3aaa5915">

**Comment by Shinmera** [comment]
Fixed in 4bc540f
