### ISSUE TITLE
Tilt controls

### ISSUE THREAD

**Issue by StevenH237** [Shinmera/promptfont#23]
Many controllers and handhelds - Nintendo starting with the Wii, Sony starting with the PS3, Steam starting with the Steam Controller, and basically any smartphone (but nothing xbox) - all have gyroscopes and support tilt controls. Glyphs for tilt actions might be nice, such as possibly:

1. Generic gyroscope icon
2. Gyroscope with rotation arrows for roll, pitch, or yaw
3. Smartphone icons with rotation arrows for roll, pitch, or yaw
4. Controller icons with rotation arrows for roll, pitch, or yaw
5. Arrows by themselves that could be overlaid on other glyphs

I'm willing to contribute glyphs for any of the last three categories myself, though I don't trust myself to make a good gyroscope icon.

**Comment by Shinmera** [comment]
Yeah, those have been on my todo #2 for ages.

**Comment by StevenH237** [comment]
Oh! I was looking for the word "Gyro" in that list, but on a further review I can clearly see "Tilt" is right there.
