### ISSUE TITLE
DPAD_LEFT_DOWN and DPAD_LEFT_DOWN_INT are declared twice in prompfont.cs

### ISSUE THREAD

**Issue by nullmoongames** [Shinmera/promptfont#25]
`DPAD_LEFT_DOWN` and `DPAD_LEFT_DOWN_INT` are declared twice.
I reckon the first two should be renamed `SONY_DPAD_LEFT_DOWN `and  `SONY_DPAD_LEFT_DOWN`

**Comment by Shinmera** [comment]
No, they're just complete duplicates in the glyph table. I removed them now.
