### ISSUE TITLE
Adding an empty keycap for keyboard letters

### ISSUE THREAD

**Issue by dortamiguel** [Shinmera/promptfont#3]
Hi, thank you very much for the font, it's really nice.

I was thinking that it will be nice to add also a keycap background for each letter in the keyboard like this ones 

![image](https://user-images.githubusercontent.com/3449006/165491132-57c3466f-83a2-4e5d-a1a3-d40c34b596c8.png)

Is it something that can be done?

Thank you

**Comment by Shinmera** [comment]
If I understand your request correctly that would require creating a multi-layered font, which is possible, but none of the tools I use support layered fonts, so I'm afraid I can't commit any time to implementing it.

**Comment by ellipticaldoor** [comment]
I see thank you

**Comment by Shinmera** [comment]
A much easier solution would be to add a general background shape in whatever engine you're using to display the font.

**Comment by ellipticaldoor** [comment]
Oh yes, just having an empty keycap will make it easy for me to layer them both

**Comment by Shinmera** [comment]
Ok, I can see about repurposing a glyph for that.

**Comment by Shinmera** [comment]
Has been added as U+248F
