### ISSUE TITLE
Click to copy character

### ISSUE THREAD

**Issue by d3kryption** [Shinmera/promptfont#6]
HI!
Great addon, love it. Use it in all my games :D

Is it possible on the website to make it so you can click to copy the character?

https://shinmera.github.io/promptfont/

I can do it via JS or inspect element but it would be a nicer UX for a user.

If I'm missing something please let me know :)

Also, first issue request! Apologies if I'm doing anything wrong :D

Thanks

**Comment by d3kryption** [comment]
This is the JS I normally apply to make it clickable

`document.querySelectorAll(".glyph").forEach(function(item) {
item.addEventListener("click", () =>  navigator.clipboard.writeText(item.querySelector("i").innerText));
})`

but it can be made a bit nicer like so:

`document.querySelectorAll(".glyph").forEach(function(item) {
	item.addEventListener("click", function() {
		let text = item.querySelector("i").innerText;
		navigator.clipboard.writeText(text)
		alert(`${text} copied!`)
	});
})`

Not sure if this helps :)

**Comment by Shinmera** [comment]
Thanks for the suggestion! Should be implemented now.

**Comment by d3kryption** [comment]
> Thanks for the suggestion! Should be implemented now.

I can't believe how quickly you added it.

I saw it added to the repo. Thank you for taking my suggestion! :D

it looks and works fantastic.
